// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import PocketAdapter from './pocketbase-adapter';
import ApiAdapter from './api-adapter';

const SUPABASE_URL = (import.meta as any).env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";
const USE_POCKETBASE = (import.meta as any).env.VITE_USE_POCKETBASE === '1' || (import.meta as any).env.VITE_USE_POCKETBASE === 'true';
const API_URL = (import.meta as any).env.VITE_API_URL ?? "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/client";

let supabase: any;

if (API_URL) {
  // Use custom Node+SQLite API when configured
  supabase = ApiAdapter;
} else {
  const shouldUsePocketBase = USE_POCKETBASE || (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY);

  if (shouldUsePocketBase) {
    // Prefer the PocketBase (SQLite) adapter if explicitly requested or if Supabase isn't configured
    supabase = PocketAdapter;
    if (!USE_POCKETBASE && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
      console.info("Using PocketBase adapter because Supabase env vars are not set.");
    }
  } else {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
}

export { supabase };